/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyFragment {
        "deferred": boolean;
    }
}
declare global {
    interface HTMLMyFragmentElement extends Components.MyFragment, HTMLStencilElement {
    }
    var HTMLMyFragmentElement: {
        prototype: HTMLMyFragmentElement;
        new (): HTMLMyFragmentElement;
    };
    interface HTMLElementTagNameMap {
        "my-fragment": HTMLMyFragmentElement;
    }
}
declare namespace LocalJSX {
    interface MyFragment {
        "deferred"?: boolean;
    }
    interface IntrinsicElements {
        "my-fragment": MyFragment;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-fragment": LocalJSX.MyFragment & JSXBase.HTMLAttributes<HTMLMyFragmentElement>;
        }
    }
}
